const projects = document.querySelector(".projects");

const data = [
  {
    id: 1,
    title: "Background Video",
    src: "../01.Background Video/index.html",
    img:  "images/img1.png",
    lang: "HTML & CSS",
  },
  {
    id: 2,
    title: "Creative Loading Animation",
    src: "../02.Creative Loading Animation/index.html",
    img:  "images/img2.png",
    lang: "HTML & CSS",
  },
  {
    id: 3,
    title: "Custom Scrollbar",
    src: "../03.Custom Scrollbar/index.html",
    img:  "images/img3.png",
    lang: "HTML & CSS",
  },
  {
    id: 4,
    title: "Creative Image Hover Effect ",
    src: "../04.Creative Image Hover Effect/index.html",
    img:  "images/img4.png",
    lang: "HTML & CSS",
  },
  {
    id: 5,
    title: "Creative Buttons",
    src: "../05.Top 5 Creative Buttons/btn1/index.html",
    img:  "images/img5.png",
    lang: "HTML & CSS",
  },
  {
    id: 6,
    title: "Creative Menu",
    src: "../06.Creative Menu/menu1/index.html",
    img:  "images/img6.png",
    lang: "HTML & CSS",
  },
  {
    id: 7,
    title: "Cretive Image Effect",
    src: "../07.Cretive Image Effect/01. Effect 1/index.html",
    img:  "images/img7.png",
    lang: "HTML & CSS",
  },
  {
    id: 8,
    title: "Creative Cards",
    src: "../08.Creative Cards/01. Card 1/index.html",
    img:  "images/img8.png",
    lang: "HTML & CSS",
  },
  {
    id: 9,
    title: "Tooltip",
    src: "../09.Tooltip/index.html",
    img:  "images/img9.png",
    lang: "HTML & CSS",
  },
  {
    id: 10,
    title: "Accordion",
    src: "../10.Accordion/index.html",
    img: "images/img10.png",
    lang: "HTML & CSS",
  },
  {
    id: 11,
    title: "Scrollbar",
    src: "../11.Scrollbar/index.html",
    img: "images/img11.png",
    lang: "HTML & CSS",
  },
  {
    id: 12,
    title: "Image Background Text",
    src: "../12.Image Background Text/index.html",
    img: "images/img12.png",
    lang: "HTML & CSS",
  },
  {
    id: 13,
    title: "Page Scroll Indicator",
    src: "../13.Page Scroll Indicator/index.html",
    img: "images/img13.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 14,
    title: "Heart",
    src: "../14.Heart/index.html",
    img: "images/img14.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 15,
    title: "Background Color Changer",
    src: "../15.Background Color Changer/index.html",
    img: "images/img15.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 16,
    title: "Auto Text",
    src: "../16.Auto Text/index.html",
    img: "images/img16.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 17,
    title: "Cursor",
    src: "../17.Cursor/index.html",
    img: "images/img17.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 18,
    title: "Video Trailer Popup",
    src: "../18.Video Trailer Popup/index.html",
    img: "images/img18.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 19,
    title: "Color Toggler",
    src: "../19.Color Toggler/index.html",
    img: "images/img19.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 20,
    title: "Animated Navigation",
    src: "../20. Animated Navigation/index.html",
    img: "images/img20.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 21,
    title: "Random Emojies",
    src: "../21.Random Emojies/index.html",
    img: "images/img21.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 22,
    title: "Fade Out",
    src: "../22.Fade Out/index.html",
    img: "images/img22.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 23,
    title: "Simple Calculator",
    src: "../23.Simple Calculator/index.html",
    img: "images/img23.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 24,
    title: "Copy and Move",
    src: "../24.Copy and Move/index.html",
    img: "images/img24.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 25,
    title: "Progress Steps",
    src: "../25.Progress Steps/index.html",
    img: "images/img25.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 26,
    title: "Lazy Loading",
    src: "../26.Lazy Loading/index.html",
    img: "images/img26.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 27,
    title: "Form Popup",
    src: "../27.Form Popup/index.html",
    img: "images/img27.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 28,
    title: "Show Hide Password",
    src: "../28.Show Hide Password/index.html",
    img: "images/img28.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 29,
    title: "Select Menu",
    src: "../29.Select Menu/index.html",
    img: "images/img29.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 30,
    title: "Form Wave",
    src: "../30.Form Wave/index.html",
    img: "images/img30.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 31,
    title: "Full Screen Navigation",
    src: "../31.Full Screen Navigation/index.html",
    img: "images/img31.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 32,
    title: "3D Navigation",
    src: "../32.3D Navigation/index.html",
    img: "images/img32.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 33,
    title: "Counter",
    src: "../33.Counter/index.html",
    img: "images/img33.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 34,
    title: "Text Formatter",
    src: "../34.Text Formatter/index.html",
    img: "images/img34.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 35,
    title: "Images Gallery",
    src: "../35.Images Gallery/index.html",
    img: "images/img35.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 36,
    title: "Read More and Read Less",
    src: "../36.Read More and Read Less/index.html",
    img: "images/img36.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 37,
    title: "Expanding Cards",
    src: "../37.Expanding Cards/index.html",
    img: "images/img37.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 38,
    title: "keyCode",
    src: "../38.keyCode/index.html",
    img: "images/img38.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 39,
    title: "Tabs",
    src: "../39.Tabs/index.html",
    img: "images/img39.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 40,
    title: "Accordions",
    src: "../40.Accordions/index.html",
    img: "images/img40.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 41,
    title: "Random Images",
    src: "../41.Random Images/index.html",
    img: "images/img41.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 42,
    title: "Random Quote",
    src: "../42.Random Quote/index.html",
    img: "images/img42.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 43,
    title: "Email validation",
    src: "../43.Email validation/index.html",
    img: "images/img43.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 44,
    title: "Interchangeable Background Color",
    src: "../44.Interchangeable Background Color/index.html",
    img: "images/img44.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 45,
    title: "Digital Clock",
    src: "../45.Digital Clock/index.html",
    img: "images/img45.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 46,
    title: "Browse File Upload",
    src: "../46.Browse File Upload/index.html",
    img: "images/img46.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 47,
    title: "Sticky Navbar",
    src: "../47.Sticky Navbar/index.html",
    img: "images/img47.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 48,
    title: "Search and Hightlight",
    src: "../48.Search and Hightlight/index.html",
    img: "images/img48.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 49,
    title: "Custom Range Slider",
    src: "../49.Custom Range Slider/index.html",
    img: "images/img49.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 50,
    title: "Feedback",
    src: "../50.Feedback/index.html",
    img: "images/img50.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 51,
    title: "Eye Follow",
    src: "../51.Eye Follow/index.html",
    img: "images/img51.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 52,
    title: "Rounded Navbar",
    src: "../52.Rounded Navbar/index.html",
    img: "images/img52.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 53,
    title: "CSS Clip Path Animation",
    src: "../53.CSS Clip Path Animation/index.html",
    img: "images/img53.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 54,
    title: "Mini Calendar",
    src: "../54.Mini Calendar/index.html",
    img: "images/img54.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 55,
    title: "Two Sides Scroll",
    src: "../55.Two Sides Scroll/index.html",
    img: "images/img55.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 56,
    title: "Followers",
    src: "../56.Followers/index.html",
    img: "images/img56.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 57,
    title: "Custom Cursor",
    src: "../57.Custom Cursor/index.html",
    img: "images/img57.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 58,
    title: "Rotating Text",
    src: "../58.Rotating Text/index.html",
    img: "images/img58.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 59,
    title: "Background Image Carousel",
    src: "../59.Background Image Carousel/index.html",
    img: "images/img59.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 60,
    title: "Modern Calculator",
    src: "../60.Modern Calculator/index.html",
    img: "images/img60.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 61,
    title: "Sidebar Animation",
    src: "../61.Sidebar Animation/index.html",
    img: "images/img61.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 62,
    title: "Rotating Image Gallery",
    src: "../62.Rotating Image Gallery/index.html",
    img: "images/img62.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 63,
    title: "Password Strength Bg",
    src: "../63.Password Strength Bg/index.html",
    img: "images/img63.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 64,
    title: "Gradient Generator",
    src: "../64.Gradient Generator/index.html",
    img: "images/img64.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 65,
    title: "Two sided Form",
    src: "../65.Two sided Form/index.html",
    img: "images/img65.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 66,
    title: "Animated Search Bar",
    src: "../66.Animated Search Bar/index.html",
    img: "images/img66.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 67,
    title: "Password Generator",
    src: "../67.Password Generator/index.html",
    img: "images/img67.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 68,
    title: "Box Shadow Generator",
    src: "../68.Box Shadow Generator/index.html",
    img: "images/img68.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 69,
    title: "Deciaml To Binary Converter",
    src: "../69.Deciaml To Binary Converter/index.html",
    img: "images/img69.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 70,
    title: "Captcha Project",
    src: "../70.Captcha Project/index.html",
    img: "images/img70.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 71,
    title: "Drag n Drop",
    src: "../71.Drag n Drop/index.html",
    img: "images/img71.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 72,
    title: "Update CSS Variables Using JS",
    src: "../72.Update CSS Variables Using JS/index.html",
    img: "images/img72.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 73,
    title: "Light",
    src: "../73.Light/index.html",
    img: "images/img73.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 74,
    title: "Tebed Navigation",
    src: "../74.Tebed Navigation/index.html",
    img: "images/img74.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 75,
    title: "Todo List",
    src: "../75.Todo List/index.html",
    img: "images/img75.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 76,
    title: "Chuck Norris",
    src: "../76.Chuck Norris/index.html",
    img: "images/img76.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 77,
    title: "Random Cat Images",
    src: "../77.Random Cat Images/index.html",
    img: "images/img77.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 78,
    title: "Dad Jokes",
    src: "../78.Dad Jokes/index.html",
    img: "images/img78.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 79,
    title: "Testimonal Box Switcher",
    src: "../79.Testimonal Box Switcher/index.html",
    img: "images/img79.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 80,
    title: "Live User Filter",
    src: "../80.Live User Filter/index.html",
    img: "images/img80.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 81,
    title: "Animated Images Website",
    src: "../81.Animated Images Website/index.html",
    img: "images/img81.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 82,
    title: "Emoji Catcher Game",
    src: "../82.Emoji Catcher Game/index.html",
    img: "images/img82.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 83,
    title: "Twitter Follow Component",
    src: "../83.Twitter Follow Component/index.html",
    img: "images/img83.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 84,
    title: "BookList Project",
    src: "../84.BookList Project/index.html",
    img: "images/img84.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 85,
    title: "Timer",
    src: "../85.Timer/index.html",
    img: "images/img85.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 86,
    title: "Typing Game",
    src: "../86.Typing Game/index.html",
    img: "images/img86.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 87,
    title: "Shape Clicker Game",
    src: "../87.Shape Clicker Game/index.html",
    img: "images/img87.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 88,
    title: "Word Counter",
    src: "../88.Word Counter/index.html",
    img: "images/img88.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 89,
    title: "Random User",
    src: "../89.Random User/index.html",
    img: "images/img89.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 90,
    title: "Construction Landing Page",
    src: "../90.Construction Landing Page/index.html",
    img: "images/img90.png",
    lang: "HTML & CSS",
  },
  {
    id: 91,
    title: "Foody Landing Page",
    src: "../91.Foody Landing Page/index.html",
    img: "images/img91.png",
    lang: "HTML & CSS",
  },
  {
    id: 92,
    title: "Coffee",
    src: "../92.Coffee/index.html",
    img: "images/img92.png",
    lang: "HTML & CSS",
  },
  {
    id: 93,
    title: "The Art",
    src: "../93.The Art/index.html",
    img: "images/img93.png",
    lang: "HTML & CSS",
  },
  {
    id: 94,
    title: "Hoodie",
    src: "../94.Hoodie/index.html",
    img: "images/img94.png",
    lang: "HTML & CSS",
  },
  {
    id: 95,
    title: "Chairs",
    src: "../95.Chairs/index.html",
    img: "images/img95.png",
    lang: "HTML & CSS",
  },
  {
    id: 96,
    title: "Meal Finder",
    src: "../96.Meal Finder/index.html",
    img: "images/img96.png",
    lang: "HTML & CSS",
  },
  {
    id: 97,
    title: "Github Profile Clone",
    src: "../97.Github Profile Clone/index.html",
    img: "images/img97.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 98,
    title: "Form Validation",
    src: "../98.Form Validation/index.html",
    img: "images/img98.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 99,
    title: "Wikipedia Clone",
    src: "../99.Wikipedia Clone/index.html",
    img: "images/img99.png",
    lang: "HTML & CSS & JavaScript",
  },
  {
    id: 100,
    title: "Global Weather",
    src: "../100.Global Weather/index.html",
    img: "images/img100.png",
    lang: "HTML & CSS & JavaScript",
  },
];


let html = '';

data.forEach((project) => {
  html += `
        <div>
            <a href="${project.src}" class="project-link">
                <div class="img-wrapper">
                    <img src="${project.img}" alt="Project ${project.id}">
                </div>
            
                <div class="title-project">
                    <h2>${project.title}</h2>
                    <p>${project.lang}</p>
                </div>
            
                <div class="btn-link">View Project
                    <div class="icon">→</div>
                </div>
            
                <div class="bottom-btn"></div>
                <div class="rounded"></div>
            </a>
        </div>
    `;
});
projects.innerHTML = html;
